### ISSUE TITLE
Possible Enhancements

### ISSUE THREAD

**Issue by Laphatize** [FHGDev/Hulkbot#4]
This is just a recommendation, but I suggest making an eval command. So, you can do something like $eval updates.push("some new update"), rather than going back into the code and adding the update.
Having an eval command is a really good idea in general.

Here's how I normally do my eval commands:
```js

if (msg.content.startsWith("eval") {

if (msg.author.id = "OWNERBOTID") {

try {
var code = msg.slice(5);
eval(code);
msg.reply("code runned")
} catch(err) {

msg.reply("There was an error with your code! I've logged it to the console.");
console.log(err)

}
} else {

msg.reply("not high enough perms")

}


}
```

Let me know if you want me to implement this directly for you guys.

**Comment by FHGDev** [comment]
Hey Laphatize! Thanks for the recommendation. We decided to follow ur advice, and make an eval command. You can view it [here](https://github.com/FHGDev/Hulkbot/tree/master/commands/eval.js).
